<?php

/** @var \AHT\Blog\Block\Index $block */
?>

<h3 style="text-align: center;"><?= $block->escapeHtml($block->getBlogInfo()); ?></h3>
<table class="table table-bordered table-striped table-hover table-reponsive scroll">
    <thead>
        <a href="<?= $block->escapeHtml($block->getBaseUrl()); ?>blog/index/create" class="btn btn-primary btn-xs pull-right">Create New Post</a>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Url Key</th>
            <th>Image</th>
            <th>Content</th>
            <th>Status</th>
            <th>Creared At</th>
            <th>Updated At</th>
            <th colspan="2">Action</th>
        </tr>
    </thead>
    <?php
    $posts = $block->getPosts();
    foreach ($posts as $post) {
        echo "<tr style=\"border: 1px solid #dddddd; text-align: left; padding: 8px;\">";
        echo "<td>" . $block->escapeHtml(__($post->getId())) . "</td>";
        echo "<td>" . $block->escapeHtml(__($post->getName())) . "</td>";
        echo '<td><a href="' . $block->escapeHtml($block->getBaseUrl()) . $block->escapeHtml($post->getUrlKey()) . '">' . $block->escapeHtml($post->getUrlKey()) . '</a></td>';
        echo "<td>" . $block->escapeHtml(__($post->getImage())) . "</td>";
        echo "<td>" . $block->escapeHtml(__($post->getContent())) . "</td>";
        echo "<td>" . $block->escapeHtml(__($post->getStatus())) . "</td>";
        echo "<td>" . $block->escapeHtml(__($post->getCreatedAt())) . "</td>";
        echo "<td>" . $block->escapeHtml(__($post->getUpdatedAt())) . "</td>";
        echo '<td><a href="' . $block->escapeHtml(__($block->getBaseUrl())) . 'blog/index/edit/post_id/' .
            $block->escapeHtml(__($post->getId())) . '" class="btn btn-primary btn-xs pull-right">Edit</a></td>';
        echo '<td><a href="' . $block->escapeHtml(__($block->getBaseUrl())) . 'blog/index/delete/post_id/' .
            $block->escapeHtml(__($post->getId())) . '" class="btn btn-primary btn-xs pull-right">Delete</a></td>';
        echo "</tr>";
    }
    ?>
</table>